/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andrewbl' at '1/27/15 9:46 PM' with Gradle 2.2.1
 *
 * @author andrewbl, @date 1/27/15 9:46 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
